var http = require('http'),
    path = require('path'),
    xml2js =require('xml2js'),
    express = require('express'),
    fs = require('fs'),
    xmlParse = require('xslt-processor').xmlParse,
    xsltProcess = require('xslt-processor').xsltProcess;

var router = express();
var server = http.createServer(router);

router.use(express.static(path.resolve(__dirname, 'views')));
router.use(express.urlencoded({extended: true}));
router.use(express.json());// Function to read in XML file and convert it to JSON

// Function to read in XML file and convert it to JSON
function xmlFileToJs(filename, cb) {
    var filepath = path.normalize(path.join(__dirname, filename));
        fs.readFile(filepath, 'utf8', function(err, xmlStr) {
        if (err) throw (err);
        xml2js.parseString(xmlStr, {}, cb);
    });
}

//Function to convert JSON to XML and save it
    function jsToXmlFile(filename, obj, cb) {
    var filepath = path.normalize(path.join(__dirname, filename));
    var builder = new xml2js.Builder();
    var xml = builder.buildObject(obj);
    fs.writeFile(filepath, xml, cb);
}

// POST request to add to JSON & XML files
router.post('/post/json', function(req, res){
    function appendJSON(obj){
    xmlFileToJs('dublinBookstore.xml', function(err, result){
        if(err) throw (err);
        result.bookstore.book[obj.sec_n].details.push({'title': obj.title,'author': obj.author,'year': obj.year, 'price': obj.price});
        console.log(result);
        jsToXmlFile('dublinBookstore.xml', result, function(err){
        if(err) console.log(err);
            })
        })
    }
    appendJSON(req.body);
    res.redirect('back');
});

// POST request to add to JSON & XML files
router.post('/post/delete', function(req, res) {

  // Function to read in a JSON file, add to it & convert to XML
  function deleteJSON(obj) {
    // Function to read in XML file, convert it to JSON, delete the required object and write back to XML file
    xmlFileToJs('dublinBookstore.xml', function(err, result) {
      if (err) throw (err);
      //This is where we delete the object based on the position of the section and position of the entree, as being passed on from index.html
      delete result.bookstore.book[obj.book].details[obj.details];
      //This is where we convert from JSON and write back our XML file
      jsToXmlFile('dublinBookstore.xml', result, function(err) {
        if (err) console.log(err);
      })
    })
  }

  // Call appendJSON function and pass in body of the current POST request
  deleteJSON(req.body);

});



//We define the root of our website and render index.html located inside the views folder
router.get('/', function(req, res){


    res.render('index');

})



//We define a new route /get/html to be rendering our HTML table that is being generated by applying XSL file to XML
router.get('/get/html', function(req, res) {

    res.writeHead(200, {'Content-Type': 'text/html'});

    var xml = fs.readFileSync('dublinBookstore.xml', 'utf8');
    var xsl = fs.readFileSync('dublinBookstore.xsl', 'utf8');
    var doc = xmlParse(xml); //Parsing our XML file
    var stylesheet = xmlParse(xsl); //Parsing our XSL file

    var result = xsltProcess(doc, stylesheet); //Execute
          
    res.end(result.toString()); //Converting the result into a string before respond to the user

});





server.listen(process.env.port || 3000, process.env.IP || "0.0.0.0", function(){
    var addr = server.address();
    console.log("Server is listening at", addr.address + ":" + addr.port);

});