var http = require('http'),
    path = require('path'),
    xml2js =require('xml2js'),
    express = require('express'),
    fs = require('fs'),
    xmlParse = require('xslt-processor').xmlParse,
    xsltProcess = require('xslt-processor').xsltProcess;

var router = express();
var server = http.createServer(router);

router.use(express.static(path.resolve(__dirname, 'views')));








 


//We define the root of our website and render index.html located inside the views folder
router.get('/', function(req, res){

    res.render('index');

})

//We define a new route /get/html to be rendering our HTML table that is being generated by applying XSL file to XML
router.get('/get/html', function(req, res) {

    res.writeHead(200, {'Content-Type': 'text/html'});

    var xml = fs.readFileSync('dublinBookstore.xml', 'utf8');
    var xsl = fs.readFileSync('dublinBookstore.xsl', 'utf8');
    var doc = xmlParse(xml); //Parsing our XML file
    var stylesheet = xmlParse(xsl); //Parsing our XSL file

    var result = xsltProcess(doc, stylesheet); //Execute
          
    res.end(result.toString()); //Converting the result into a string before respond to the user






});

